# Terminal donation formula

DONATION_FORMULA_CLASSIC = "Classique"
DONATION_FORMULA_FREE = "Gratuit"
DONATION_FORMULA_MECENAT = "Mécénat"
DONATION_FORMULA_SHARE = "Partage"

DONATION_FORMULAS = (
    (DONATION_FORMULA_CLASSIC, "Classique"),
    (DONATION_FORMULA_FREE, "Gratuit"),
    (DONATION_FORMULA_MECENAT, "Mécénat"),
    (DONATION_FORMULA_SHARE, "Partage"),
)
