# Generated by Django 3.0.3 on 2020-10-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='photo50',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/actions/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='text50',
            field=models.TextField(blank=True, null=True),
        ),
    ]
