# Generated by Django 3.0.3 on 2020-03-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20200302_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='text10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='text20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='text30',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='text5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
