# Generated by Django 3.0.3 on 2020-10-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20201001_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(default='Microsoft', max_length=255),
            preserve_default=False,
        ),
    ]
