# Generated by Django 3.0.3 on 2020-03-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20200302_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
