# Generated by Django 3.0.3 on 2020-10-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20201003_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='featured_image',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/images/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_video',
            field=models.BooleanField(default=True),
        ),
    ]
