# Generated by Django 3.0.3 on 2020-10-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_auto_20201003_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='featured_image',
        ),
    ]
