# Generated by Django 3.0.3 on 2021-03-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_customer_maintenance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='photo10',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='photo20',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='photo30',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='photo50',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text10',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text20',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text30',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text50',
        ),
        migrations.CreateModel(
            name='DonationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='campaigns/actions/')),
                ('text', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationSteps', to='fleet.Campaign')),
            ],
        ),
    ]
