# Generated by Django 3.0.3 on 2021-06-02 12:19

from django.db import migrations, models
import django.db.models.deletion

def camapign_to_donationstep(apps, schema_editor):
    Campaign = apps.get_model("fleet", "Campaign")
    DonationStep = apps.get_model("fleet", "DonationStep")
    
    for campaign in Campaign.objects.all():
        step1 = DonationStep.objects.create(
            amount = 1,
            image = campaign.photo1,
            text = campaign.text1
        )
        step1.campaign = campaign
        step1.save()

        step5 = DonationStep.objects.create(
            amount = 5,
            image = campaign.photo5,
            text = campaign.text5
        )
        step5.campaign = campaign
        step5.save()

        step10 = DonationStep.objects.create(
            amount = 10,
            image = campaign.photo10,
            text = campaign.text10
        )
        step10.campaign = campaign
        step10.save()

        step20 = DonationStep.objects.create(
            amount = 20,
            image = campaign.photo20,
            text = campaign.text20
        )
        step20.campaign = campaign
        step20.save()

        step30 = DonationStep.objects.create(
            amount = 30,
            image = campaign.photo30,
            text = campaign.text30
        )
        step30.campaign = campaign
        step30.save()

        step50 = DonationStep.objects.create(
            amount = 50,
            image = campaign.photo50,
            text = campaign.text50
        )
        step50.campaign = campaign
        step50.save()

def donationstep_to_campaing(apps, schema_editor):
    Campaign = apps.get_model("fleet", "Campaign")
    DonationStep = apps.get_model("fleet", "DonationStep")

    for step in DonationStep.objects.all():
        campaign = Campaign.objects.get(pk=step.campaign)

        if campaign.amount >= 1 and campaign.amount < 5:
            campaign.photo1 = step.image
            campaign.text1 = step.text
        elif campaign.amount >= 5 and campaign.amount < 10:
            campaign.photo5 = step.image
            campaign.text5 = step.text
        elif campaign.amount >= 10 and campaign.amount < 20:
            campaign.photo10 = step.image
            campaign.text10 = step.text
        elif campaign.amount >= 20 and campaign.amount < 30:
            campaign.photo20 = step.image
            campaign.text20 = step.text
        elif campaign.amount >= 30 and campaign.amount < 50:
            campaign.photo30 = step.image
            campaign.text30 = step.text
        elif campaign.amount >= 50 :
            campaign.photo50 = step.image
            campaign.text50 = step.text

class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_customer_maintenance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='campaigns/actions/')),
                ('text', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donationSteps', to='fleet.Campaign')),
            ],
            options={'ordering': ['amount']},
        ),
        
        migrations.RunPython(camapign_to_donationstep, reverse_code=donationstep_to_campaing),

        migrations.RemoveField(
            model_name='campaign',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='photo10',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='photo20',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='photo30',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='photo50',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text10',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text20',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text30',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='text50',
        ),
    ]
