# Generated by Django 3.0.3 on 2021-03-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_auto_20210309_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationstep',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donationSteps', to='fleet.Campaign'),
        ),
    ]
