# Generated by Django 3.0.3 on 2022-07-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_customer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/covers/'),
        ),
    ]
