# Generated by Django 3.0.3 on 2021-05-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_auto_20210318_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationStep',
        ),
    ]
