# Generated by Django 3.0.3 on 2021-05-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_donationstep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationStep',
        ),
    ]
