# Generated by Django 3.0.3 on 2022-09-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_campaign_squared_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
