# Generated by Django 3.0.3 on 2022-09-19 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_campaign_squared_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='login_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='login_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('terminal', 'Terminal'), ('customer', 'Client')], max_length=8, null=True, verbose_name="Type d'utilisateur"),
        ),
    ]
