# Generated by Django 3.0.3 on 2022-09-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_remove_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='customer',
        ),
    ]
