# Generated by Django 3.0.3 on 2021-05-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_donationstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationstep',
            name='photo',
        ),
    ]
