# Generated by Django 3.0.3 on 2022-09-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Asso du moment'),
        ),
    ]
