# Generated by Django 3.0.3 on 2021-05-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_remove_donationstep_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationstep',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/actions/'),
        ),
    ]
