# Generated by Django 3.0.3 on 2021-05-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_donationstep_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationstep',
            name='image',
        ),
    ]
