# Generated by Django 3.0.3 on 2022-10-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_campaign_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='can_edit_donation_formula',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='can_edit_featured_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='can_edit_screensaver_broadcasts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='can_see_donators',
            field=models.BooleanField(default=False),
        ),
    ]
