# Generated by Django 3.0.3 on 2021-05-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_donationstep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationstep',
            name='amount',
            field=models.IntegerField(blank=True),
        ),
    ]
