# Generated by Django 3.0.3 on 2022-10-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_game_featured'),
        ('fleet', '0016_auto_20221013_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='featured_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.Campaign'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='featured_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Game'),
        ),
    ]
