# Generated by Django 3.0 on 2019-12-25 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('accept_asso', models.BooleanField(blank=True, default=False, null=True)),
                ('accept_newsletter', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='games/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_on', models.BooleanField(default=False)),
                ('is_playing', models.BooleanField(default=False)),
                ('campaigns', models.ManyToManyField(to='fleet.Campaign')),
                ('games', models.ManyToManyField(to='terminal.Game')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='terminal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_global', models.DateTimeField(blank=True, null=True)),
                ('end_global', models.DateTimeField(blank=True, null=True)),
                ('position_asso', models.IntegerField()),
                ('timesession', models.DurationField(blank=True, null=True)),
                ('timesession_global', models.DurationField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='fleet.Campaign')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='terminal.Donator')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='terminal.Game')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='terminal.Terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fleet.Campaign')),
                ('donator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='terminal.Donator')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='terminal.Game')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='terminal.Terminal')),
            ],
        ),
    ]
