# Generated by Django 3.0.3 on 2020-09-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('terminal', '0002_auto_20200928_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='core',
        ),
        migrations.RemoveField(
            model_name='game',
            name='file',
        ),
        migrations.AlterField(
            model_name='payment',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='game.Game'),
        ),
        migrations.AlterField(
            model_name='session',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='game.Game'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='games',
            field=models.ManyToManyField(related_name='terminals', to='game.Game'),
        ),
        migrations.DeleteModel(
            name='Core',
        ),
        migrations.DeleteModel(
            name='CoreFile',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameFile',
        ),
    ]
