# Generated by Django 3.0.3 on 2020-10-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_terminal_play_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
