# Generated by Django 3.0.3 on 2021-11-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_terminal_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
