# Generated by Django 3.0.3 on 2022-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_terminal_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='free_mode_text',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
