# Generated by Django 3.0.3 on 2022-05-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0007_terminal_free_mode_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='payment_terminal',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='free_mode_text',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
