# Generated by Django 3.0.3 on 2022-07-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0008_auto_20220514_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='donation_formula',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
