# Generated by Django 3.0.3 on 2022-07-16 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminal', '0011_remove_terminal_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal', to=settings.AUTH_USER_MODEL),
        ),
    ]
