# Generated by Django 3.0.3 on 2022-07-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0013_auto_20220716_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='donation_formula',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='payment_terminal',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
