# Generated by Django 3.0.3 on 2022-07-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0014_auto_20220717_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='payment_terminal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
