# Generated by Django 3.0.3 on 2022-09-22 14:46

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone

def populate_username_and_password(apps, schema_editor):
    TerminalModel = apps.get_model('terminal', 'Terminal')
    for terminal_object in TerminalModel.objects.all():
        terminal_object.username = terminal_object.owner.username
        terminal_object.password = terminal_object.owner.password
        terminal_object.save(update_fields=['username', 'password'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('terminal', '0015_auto_20220723_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'verbose_name': 'Terminal', 'verbose_name_plural': 'Terminaux'},
        ),
        migrations.AlterModelManagers(
            name='terminal',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='terminal',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this terminal belongs to. A terminal will get all permissions granted to each of their groups.', related_name='terminal_set', related_query_name='terminal', to='auth.Group', verbose_name='Groups de permissions'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this terminal.', related_name='terminal_set', related_query_name='terminal', to='auth.Permission', verbose_name="Permissions d'utilisateur"),
        ),

        # Add field username as non unique and provide one off default value, same for all rows
        
        migrations.AddField(
            model_name='terminal',
            name='username',
            field=models.CharField(
                default='default_username',
                error_messages={'unique': 'A user with that username already exists.'},
                help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name='username'
            ),
            preserve_default=False,
        ),

        # Add field password and provide one off default value, same for all rows

        migrations.AddField(
            model_name='terminal',
            name='password',
            field=models.CharField(default='default_password', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),

        # Run python to populate username and password

        migrations.RunPython(populate_username_and_password, reverse_code=migrations.RunPython.noop),

        # Alter field username to set it as unique

        migrations.AlterField(
            model_name='terminal',
            name='username',
            field=models.CharField(
                default='default_username',
                error_messages={'unique': 'A user with that username already exists.'},
                help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name='username'
            ),
            preserve_default=False,
        ),
    ]
