# Generated by Django 3.0.3 on 2022-10-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0016_terminal_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='donation_formula',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_terminal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='donation_default_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='terminal',
            name='donation_max_amount',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='terminal',
            name='donation_min_amount',
            field=models.IntegerField(default=1),
        ),
    ]
