# Generated by Django 3.0.3 on 2022-12-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0017_auto_20221013_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='donation_share',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='terminal',
            name='donation_share',
            field=models.IntegerField(default=50),
        ),
    ]
