# Generated by Django 3.0.3 on 2022-12-12 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0018_auto_20221209_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='donation_share',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)]),
        ),
    ]
