# Generated by Django 3.0.3 on 2023-01-04 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0019_auto_20221212_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='donation_share',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_donated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='donation_formula',
            field=models.CharField(blank=True, choices=[('Classique', 'Classique'), ('Gratuit', 'Gratuit'), ('Mécénat', 'Mécénat'), ('Partage', 'Partage')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='donation_formula',
            field=models.CharField(choices=[('Classique', 'Classique'), ('Gratuit', 'Gratuit'), ('Mécénat', 'Mécénat'), ('Partage', 'Partage')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='donation_share',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)]),
        ),
    ]
