# Generated by Django 3.0.3 on 2023-04-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0022_auto_20230327_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='payment_terminal_type',
            field=models.CharField(choices=[('PAYTER', 'PAYTER'), ('PAX', 'PAX')], default='PAYTER', max_length=10, verbose_name='Type de terminal de paiement'),
        ),
    ]
