# Generated by Django 3.0.3 on 2023-06-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0023_terminal_payment_terminal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date et heure (UTC)'),
        ),
    ]
