# Generated by Django 3.0.3 on 2023-11-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0024_auto_20230606_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='restart',
            field=models.BooleanField(default=False),
        ),
    ]
