# Generated by Django 3.0.3 on 2024-01-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminal", "0025_terminal_restart"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminal",
            name="last_restarted",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="La borne a redémarré pour la dernière fois le",
            ),
        ),
        migrations.AddField(
            model_name="terminal",
            name="restart_every_day_from",
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name="Redémarrer tous les jours à partir de",
            ),
        ),
        migrations.AddField(
            model_name="terminal",
            name="restart_every_day_until",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Redémarrer tous les jours jusqu'à"
            ),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="restart",
            field=models.BooleanField(
                default=False, verbose_name="Dire à la borne de redémarrer une fois"
            ),
        ),
    ]
