# Generated by Django 3.0.3 on 2020-09-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoreFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='games/cores/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='games/roms/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='games/logos/')),
                ('is_archived', models.BooleanField(default=False)),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.Core')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.GameFile')),
            ],
        ),
        migrations.AddField(
            model_name='core',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.CoreFile'),
        ),
    ]
