# Generated by Django 3.0.3 on 2020-09-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200929_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='file2',
        ),
    ]
