# Generated by Django 3.0.3 on 2020-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20201003_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='btn_a',
            field=models.CharField(blank=True, default='Rien', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='btn_b',
            field=models.CharField(blank=True, default='Rien', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='btn_l',
            field=models.CharField(blank=True, default='Rien', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='btn_r',
            field=models.CharField(blank=True, default='Rien', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='btn_x',
            field=models.CharField(blank=True, default='Rien', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='btn_y',
            field=models.CharField(blank=True, default='Rien', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='j_down',
            field=models.CharField(blank=True, default='Bas', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='j_left',
            field=models.CharField(blank=True, default='Gauche', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='j_right',
            field=models.CharField(blank=True, default='Droite', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='j_up',
            field=models.CharField(blank=True, default='Haut', max_length=255, null=True),
        ),
    ]
