# Generated by Django 3.0.3 on 2020-10-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201003_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nb_players',
            field=models.IntegerField(blank=True, default=1, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(blank=True, default='Unique', max_length=255, null=True),
        ),
    ]
