# Generated by Django 3.0.3 on 2020-10-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20201003_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nb_players',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
