# Generated by Django 3.0.3 on 2022-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_game_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Jeux du moment'),
        ),
    ]
