# Generated by Django 3.0.3 on 2023-02-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_game_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='execution_script',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Script de lancement'),
        ),
        migrations.AddField(
            model_name='game',
            name='installation_script',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Script d'installation"),
        ),
        migrations.AddField(
            model_name='game',
            name='kill_script',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Script d'arrêt"),
        ),
    ]
