# Generated by Django 3.0.3 on 2023-06-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20230203_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='core',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='game.Core', verbose_name='Fichier core'),
        ),
        migrations.AlterField(
            model_name='game',
            name='execution_script',
            field=models.TextField(blank=True, null=True, verbose_name='Script de lancement'),
        ),
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rom', to='game.GameFile', verbose_name="Fichier rom ou fichier d'installation"),
        ),
        migrations.AlterField(
            model_name='game',
            name='installation_script',
            field=models.TextField(blank=True, null=True, verbose_name="Script d'installation"),
        ),
        migrations.AlterField(
            model_name='game',
            name='kill_script',
            field=models.TextField(blank=True, null=True, verbose_name="Script d'arrêt"),
        ),
        migrations.AlterField(
            model_name='game',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Nom du fichier rom ou répertoire du jeu sur Hera'),
        ),
    ]
