# Generated by Django 3.0.3 on 2023-01-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screensaver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screensavermedia",
            name="youtube_video_id",
            field=models.CharField(max_length=255, verbose_name="Id de la vidéo Vimeo"),
        ),
        migrations.RenameField(
            model_name="screensavermedia",
            old_name="youtube_video_id",
            new_name="vimeo_video_id",
        ),
    ]
